-- Resposta Exercício 2: ordenação Múltipla em Consulta Composta
SELECT E.NUMERO_CONTA, T.TIPO, R.VALOR
FROM PXC.EXTRATO E
INNER JOIN PXC.REGISTRO R ON E.ID = R.ID_EXTRATO
INNER JOIN PXC.TIPO_REGISTRO T ON R.ID_TIPO = T.ID
ORDER BY T.TIPO ASC, R.VALOR ASC;