-- Resposta Exercício 4: autojunção (Self Join)
SELECT R1.ID AS ID_REGISTRO_1, R1.VALOR, R2.ID AS ID_REGISTRO_2, R2.VALOR
FROM PXC.REGISTRO R1
INNER JOIN PXC.REGISTRO R2
ON R1.ID_EXTRATO = R2.ID_EXTRATO
AND R1.VALOR <> R2.VALOR;
