-- Resposta Exercício 3: contagem com JOIN
SELECT E.NOME_TITULAR, COUNT(R.ID) AS QuantidadeMovimentacoes
FROM PXC.REGISTRO R
INNER JOIN PXC.EXTRATO E ON R.ID_EXTRATO = E.ID
GROUP BY E.NOME_TITULAR;
