-- Resposta Exercício 4: consulta com Subconsulta
SELECT E.NOME_TITULAR
FROM PXC.REGISTRO R
INNER JOIN PXC.EXTRATO E ON R.ID_EXTRATO = E.ID
WHERE R.VALOR > (SELECT AVG(VALOR) FROM PXC.REGISTRO);
