-- Resposta Exercício 5: consulta com HAVING
SELECT E.NOME_TITULAR, SUM(R.VALOR) AS TotalMovimentacoes
FROM PXC.REGISTRO R
INNER JOIN PXC.EXTRATO E ON R.ID_EXTRATO = E.ID
GROUP BY E.NOME_TITULAR
HAVING SUM(R.VALOR) > 1000;
